on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-go@v3'
        with:
          go-version-file: go.mod

      - run: make ci-tidy
      - run: make staticcheck
      - run: make fieldalignment
      - run: make test-short
      - run: make test

